### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by InnovaHacker** [SigPloiter/SigPloit#108]
After a few days the sigploit turned on, suddenly the following message came in sigploit...
Message                              Category
   --------                             --------
   0) UpdateLocation-SMS Interception    CAT3

   or type back to go back to Attacks Menu
?[37m(?[0m?[2;31mInterception?[0m?[37m)>?[0m 0
*********************************************
***              Intercepting             ***
*********************************************
?[34m[*]?[0mSet Client PC: 1127.0.0.0
?[31m[-]?[0mError: java.util.InputMismatchException
Exception in thread "main" java.lang.RuntimeException: java.util.InputMismatchEx
ception
        at UlLowLevel.init(UlLowLevel.java:106)
        at UlLowLevel.<init>(UlLowLevel.java:54)
        at UpdateLocation.<init>(UpdateLocation.java:86)
        at UpdateLocation.main(UpdateLocation.java:410)
Caused by: java.util.InputMismatchException
        at java.util.Scanner.throwFor(Unknown Source)
        at java.util.Scanner.next(Unknown Source)
        at java.util.Scanner.nextInt(Unknown Source)
        at java.util.Scanner.nextInt(Unknown Source)
        at UlLowLevel.init(UlLowLevel.java:63)
        ... 3 more
?[31mUpdateLocation Failed to Launch, Error:

**Comment by SigPloiter** [comment]
The point code (PC) is not in IP format , in normal cases it's 5 digit
number , but if ur using the lab please follow the parameters set which
normal as the below

Client PC; 1
Peer PC: 2
