### ISSUE TITLE
EOFE error

### ISSUE THREAD

**Issue by psychomad** [SigPloiter/SigPloit#11]
Hi, maybe is a stupid question but also googlein i can't get out from this problem.. any suggestion?
(im not a python coder, just learned what i need to run and modify tools)
Thanks in advance
Output error:
OS: Kali 2017 upgraded 

sig> Traceback (most recent call last):
  File "SiGploit.py", line 233, in <module>
    mainMenu()
  File "SiGploit.py", line 206, in mainMenu
    choice = raw_input("\033[34msig\033[0m\033[37m>\033[0m ")
EOFError

**Comment by SigPloiter** [comment]
i will check this error and feedback you. Thanks for your patience

**Comment by SigPloiter** [comment]
did that occur after supplying an input?

**Comment by SigPloiter** [comment]
can you please tell me what is the steps you made to reach this error and the python version you have

**Comment by psychomad** [comment]
Hi 
Sry for dealy in answering u

Python 2.7.13 
[GCC 6.3.0 20170118] on linux2

Impossible supply an input because the error occour at 
sig>
without give any input previously

**Comment by SigPloiter** [comment]
so it occurs after running ./SigPloit.py ?

**Comment by psychomad** [comment]
no i use 
#python SiGploit.py
If i use ./SiGploit.py i get  "permission denied"

**Comment by SigPloiter** [comment]
Try it as follows "sudo python SiGploit.py"

**Comment by djtroby** [comment]
Or else give permission in bin...chmod +x SiGploit.py

**Comment by Olloyor7** [comment]
python sigploit.py
Traceback (most recent call last):
  File "sigploit.py", line 16, in <module>
    from ss7.tracking import *
  File "/home/z/SigPloit/ss7/tracking.py", line 14, in <module>
    import sigploit
  File "/home/z/SigPloit/sigploit.py", line 21, in <module>
    from gtpmain import *
  File "/home/z/SigPloit/gtpmain.py", line 12, in <module>
    import gtp.info
  File "/home/z/SigPloit/gtp/info.py", line 18, in <module>
    from attacks.info import discover_gtp_nodes
  File "/home/z/SigPloit/gtp/attacks/info/discover_gtp_nodes.py", line 39, in <module>
    from gtp_v2_core.utilities.configuration_parser import parseConfigs
  File "/home/z/SigPloit/gtp/gtp_v2_core/utilities/configuration_parser.py", line 40, in <module>
    from gtp_v2_core.tunnel_mgmt_messages.create_bearer import CreateBearerRequest, CreateBearerResponse
  File "/home/z/SigPloit/gtp/gtp_v2_core/tunnel_mgmt_messages/create_bearer.py", line 34, in <module>
    from gtp_v2_core.commons.gtp_v2_msg_base import GTPV2MessageBase
  File "/home/z/SigPloit/gtp/gtp_v2_core/commons/gtp_v2_msg_base.py", line 36, in <module>
    from gtp_v2_information_element_base import *
  File "/home/z/SigPloit/gtp/gtp_v2_core/commons/gtp_v2_information_element_base.py", line 9, in <module>
    from IPy import IP
ImportError: No module named IPy
