### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by TIYYA** [SigPloiter/SigPloit#136]
root@kali:~/SigPloit# python sigploit.py
Traceback (most recent call last):
  File "sigploit.py", line 16, in <module>
    from ss7.tracking import *
  File "/root/SigPloit/ss7/tracking.py", line 14, in <module>
    import sigploit
  File "/root/SigPloit/sigploit.py", line 21, in <module>
    from gtpmain import *
  File "/root/SigPloit/gtpmain.py", line 12, in <module>
    import gtp.info
  File "/root/SigPloit/gtp/info.py", line 18, in <module>
    from attacks.info import discover_gtp_nodes
ImportError: No module named attacks.info

**Comment by SigPloiter** [comment]
should be fixed now

**Comment by TIYYA** [comment]
ss7 hack tutorial VIDEO

**Comment by SigPloiter** [comment]
Please U need to know more about SS7

**Comment by rohimsakti** [comment]
Traceback (most recent call last):
  File "sigploit.py", line 16, in <module>
    from ss7.tracking import *
  File "/root/SigPloit/ss7/tracking.py", line 14, in <module>
    import sigploit
  File "/root/SigPloit/sigploit.py", line 21, in <module>
    from gtpmain import *
  File "/root/SigPloit/gtpmain.py", line 12, in <module>
    import gtp.info
  File "/root/SigPloit/gtp/info.py", line 18, in <module>
    from attacks.info import discover_gtp_nodes
  File "/root/SigPloit/gtp/attacks/info/discover_gtp_nodes.py", line 39, in <module>
    from gtp_v2_core.utilities.configuration_parser import parseConfigs
  File "/root/SigPloit/gtp/gtp_v2_core/utilities/configuration_parser.py", line 38, in <module>
    from configobj import ConfigObj, ConfigObjError
ImportError: No module named configobj

**Comment by rohimsakti** [comment]
hai sigploiter.. can you help to fix it?
