### ISSUE TITLE
issue with pyfiglet 

### ISSUE THREAD

**Issue by soupnatzi** [SigPloiter/SigPloit#141]
python sigploit.py
Traceback (most recent call last):
  File "sigploit.py", line 16, in <module>
    from ss7.tracking import *
  File "/root/Desktop/newtools/SigPloit/ss7/tracking.py", line 14, in <module>
    import sigploit
  File "/root/Desktop/newtools/SigPloit/sigploit.py", line 25, in <module>
    from pyfiglet import figlet_format
ImportError: No module named pyfiglet

pip install pyfiglet
Requirement already satisfied: pyfiglet in /usr/local/lib/python3.6/dist-packages (0.7.5)

how can i resolve this issue?

**Comment by SigPloiter** [comment]
your default is python3, use "pip2" and change your default python to python2 instead of python3
