### ISSUE TITLE
error sigploit.py

### ISSUE THREAD

**Issue by rohimsakti** [SigPloiter/SigPloit#172]
root@kali:~/SigPloit# python sigploit.py
Traceback (most recent call last):
  File "sigploit.py", line 16, in <module>
    from ss7.tracking import *
  File "/root/SigPloit/ss7/tracking.py", line 14, in <module>
    import sigploit
  File "/root/SigPloit/sigploit.py", line 21, in <module>
    from gtpmain import *
  File "/root/SigPloit/gtpmain.py", line 12, in <module>
    import gtp.info
  File "/root/SigPloit/gtp/info.py", line 18, in <module>
    from attacks.info import discover_gtp_nodes
  File "/root/SigPloit/gtp/attacks/info/discover_gtp_nodes.py", line 39, in <module>
    from gtp_v2_core.utilities.configuration_parser import parseConfigs
  File "/root/SigPloit/gtp/gtp_v2_core/utilities/configuration_parser.py", line 38, in <module>
    from configobj import ConfigObj, ConfigObjError
ImportError: No module named configobj

**Comment by SigPloiter** [comment]
please run 
sudo pip2 install -r requirements.txt

**Comment by rohimsakti** [comment]
root@kali:~/SigPloit# python sigploit.py
Traceback (most recent call last):
  File "sigploit.py", line 16, in <module>
    from ss7.tracking import *
  File "/root/SigPloit/ss7/tracking.py", line 14, in <module>
    import sigploit
  File "/root/SigPloit/sigploit.py", line 21, in <module>
    from gtpmain import *
  File "/root/SigPloit/gtpmain.py", line 12, in <module>
    import gtp.info
  File "/root/SigPloit/gtp/info.py", line 18, in <module>
    from attacks.info import discover_gtp_nodes
  File "/root/SigPloit/gtp/attacks/info/discover_gtp_nodes.py", line 39, in <module>
    from gtp_v2_core.utilities.configuration_parser import parseConfigs
  File "/root/SigPloit/gtp/gtp_v2_core/utilities/configuration_parser.py", line 38, in <module>
    from configobj import ConfigObj, ConfigObjError
ImportError: No module named configobj

**Comment by rohimsakti** [comment]
its same error..

**Comment by rohimsakti** [comment]
root@kali:~/SigPloit# ls
gtp          __init__.py  requirements.txt  ss7          Testing
gtpmain.py   LICENSE      sigploit.py       ss7main.py
gtpmain.pyc  README.md    sigploit.pyc      ss7main.pyc
root@kali:~/SigPloit#

**Comment by rohimsakti** [comment]
> please run
> sudo pip2 install -r requirements.txt

its done but still error

**Comment by SigPloiter** [comment]
please make sure you have the latest version of the requirements.txt

**Comment by adhyushpm** [comment]
Try python2

**Comment by omprakashpuniya5132** [comment]
![15875067294592076417468564754817](https://user-images.githubusercontent.com/64031702/79918602-5d8a1c00-844a-11ea-9f6d-f9fd8d05efb3.jpg)

**Comment by mamanga1** [comment]
kali@kali:~/SigPloit$ sudo pip3 install -r requirements.txt
Requirement already satisfied: colorama>=0.3.9 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (0.4.3)
Requirement already satisfied: pyfiglet>=0.7.5 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (0.8.post0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 3)) (1.1.0)
Requirement already satisfied: configobj>=5.0.6 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 4)) (5.0.6)
Requirement already satisfied: IPy>=0.83 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 5)) (1.0)
Collecting pysctp>=0.6
  Downloading pysctp-0.6.1.tar.gz (32 kB)
Building wheels for collected packages: pysctp
  Building wheel for pysctp (setup.py) ... done
  Created wheel for pysctp: filename=pysctp-0.6.1-cp38-cp38-linux_x86_64.whl size=68787 sha256=1d508f09845fa0d1807fe8242b0cfbd11514ac07867873a3d774d5029fac3886
  Stored in directory: /root/.cache/pip/wheels/a7/79/cf/5e65fa01197e20b3b9b33b0b85eadc426c72976c14323a955a
Successfully built pysctp
Installing collected packages: pysctp
Successfully installed pysctp-0.6.1
kali@kali:~/SigPloit$ python sigploit.py
Traceback (most recent call last):
  File "sigploit.py", line 16, in <module>
    from ss7.tracking import *
  File "/home/kali/SigPloit/ss7/tracking.py", line 14, in <module>
    import sigploit
  File "/home/kali/SigPloit/sigploit.py", line 21, in <module>
    from gtpmain import *
  File "/home/kali/SigPloit/gtpmain.py", line 12, in <module>
    import gtp.info
  File "/home/kali/SigPloit/gtp/info.py", line 18, in <module>
    from attacks.info import discover_gtp_nodes
  File "/home/kali/SigPloit/gtp/attacks/info/discover_gtp_nodes.py", line 39, in <module>
    from gtp_v2_core.utilities.configuration_parser import parseConfigs
  File "/home/kali/SigPloit/gtp/gtp_v2_core/utilities/configuration_parser.py", line 38, in <module>
    from configobj import ConfigObj, ConfigObjError
ImportError: No module named configobj

**Comment by mamanga1** [comment]
sudo pip3 install configobj
Requirement already satisfied: configobj in /usr/lib/python3/dist-packages (5.0.6)
kali@kali:~/SigPloit$ python sigploit.py
Traceback (most recent call last):
  File "sigploit.py", line 16, in <module>
    from ss7.tracking import *
  File "/home/kali/SigPloit/ss7/tracking.py", line 14, in <module>
    import sigploit
  File "/home/kali/SigPloit/sigploit.py", line 21, in <module>
    from gtpmain import *
  File "/home/kali/SigPloit/gtpmain.py", line 12, in <module>
    import gtp.info
  File "/home/kali/SigPloit/gtp/info.py", line 18, in <module>
    from attacks.info import discover_gtp_nodes
  File "/home/kali/SigPloit/gtp/attacks/info/discover_gtp_nodes.py", line 39, in <module>
    from gtp_v2_core.utilities.configuration_parser import parseConfigs
  File "/home/kali/SigPloit/gtp/gtp_v2_core/utilities/configuration_parser.py", line 38, in <module>
    from configobj import ConfigObj, ConfigObjError
ImportError: No module named configobj

**Comment by Travon112200** [comment]
I also am getting this error what’s happening
