### ISSUE TITLE
Sigploit

### ISSUE THREAD

**Issue by Keskebeu** [SigPloiter/SigPloit#179]
n Vectors retrieval

   or type back to go back to Attacks Menu
(fraud)> 0
Traceback (most recent call last):
  File "sigploit.py", line 208, in <module>
    mainMenu()
  File "sigploit.py", line 173, in mainMenu
    ss7main.attacksMenu()
  File "/home/imsi/sigploit/ss7main.py", line 176, in attacksMenu
    ss7fraud()
  File "/home/imsi/sigploit/ss7main.py", line 124, in ss7fraud
    ss7fraud()
  File "/home/imsi/sigploit/ss7main.py", line 112, in ss7fraud
    ss7.fraud.simsi()
  File "/home/imsi/sigploit/ss7/fraud.py", line 28, in simsi
    sendIMSI = check_call(['java', '-jar', os.path.join(simsi_path, jar_file)])
  File "/usr/lib/python2.7/subprocess.py", line 185, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by SigPloiter** [comment]
Ol I will check and get back

**Comment by Keskebeu** [comment]
Thank you

**Comment by dydfrancis** [comment]
please i need video tutorial on this sigploit  nwosuizuchukwu511@yahoo.com thanks

**Comment by civicvchackoC3** [comment]
how to fix this error
python sigploit.py
Traceback (most recent call last):
  File "sigploit.py", line 16, in <module>
    from ss7.tracking import *
  File "/root/SigPloit/ss7/tracking.py", line 14, in <module>
    import sigploit
  File "/root/SigPloit/sigploit.py", line 24, in <module>
    from termcolor import cprint
ImportError: No module named termcolor

**Comment by dydfrancis** [comment]
boss please i need help on this i dont how to use i have ask my service provider but they cant help im from nigeria please contact me dydfrancis10@gmail.com

**Comment by AhmedHarby-art** [comment]
Please I need help in elmasry54341@gmail.com

**Comment by SigPloiter** [comment]
Please state your issue here ,send the output of the error and a packet
capture if possible

**Comment by AhmedHarby-art** [comment]
sendRoutingInfo = check_call(['java', '-jar', os.path.join(sri_path, jar_file)])
  File "/usr/lib/python2.7/subprocess.py", line 185, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Need help ; elmasry54341@gmail.com

**Comment by ashiq001** [comment]
Traceback (most recent call last):                                  File "sigploit.py", line 208, in <module>                           mainMenu()                                                      File "sigploit.py", line 173, in mainMenu
    ss7main.attacksMenu()                                           File "/data/data/com.termux/files/home/SigPloit/ss7main.py", line 173, in attacksMenu                                                 ss7interception()
  File "/data/data/com.termux/files/home/SigPloit/ss7main.py", line 82, in ss7interception
    ss7.interception.ul()                                           File "/data/data/com.termux/files/home/SigPloit/ss7/interception.py", line 24, in ul                                                  updateLocation = check_call(['java', '-jar', os.path.join(ul_path, jar_file)])                                                    File "/data/data/com.termux/files/usr/lib/python2.7/subprocess.py", line 185, in check_call                                           retcode = call(*popenargs, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()                       File "/data/data/com.termux/files/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/data/data/com.termux/files/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
 How to fix gmail me muhammadashiq2001@gmail.com

**Comment by jat28468** [comment]
bro how to set peer ip what is peer ip please tell me     and how to setup hlrlook up in ss7

**Comment by smit-agravat** [comment]
__init__.py  dos.py    interception.py
attacks      fraud.py  tracking.py
root@localhost:~/SigPloit/ss7# python tracking.py
Traceback (most recent call last):
  File "tracking.py", line 14, in <module>
    import sigploit
ImportError: No module named sigploit
root@localhost:~/SigPloit/ss7#


What to do ?

**Comment by SigPloiter** [comment]
@civicvchackoC3 either pip install termcolor or just run pip install -r requirements

**Comment by SigPloiter** [comment]
@smit-agravat @AhmedHarby-art @ashiq001 please show how do you run it

**Comment by SigPloiter** [comment]
@jat28468 you need to read more about SS7 and here is not the place for hlr-lookups

**Comment by GIDEON010** [comment]
I follow the procedure until I get..

*]Stack components are set...
[*]Initializing the Stack...
[*]Initializing SCTP Stack ....
log4j:WARN No appenders could be found for logger (org.mobicents.protocols.sctp.ManagementImpl).
log4j:WARN Please initialize the log4j system properly.
[+]Initialized SCTP Stack ....
[*]Initializing M3UA Stack ....
[+]Initialized M3UA Stack ....
[*]Initializing SCCP Stack ....
[+]Initialized SCCP Stack ....
[*]Initializing TCAP Stack ....
[+]Initialized TCAP Stack ....
[*]Initializing MAAP Stack ....
[+]Initialized MAP Stack ....
[*]Locating Target: xxxxxxxxxxxx
[*]Location Retrieval for Target xxxxxxxxxxxx is processing..

[-]Error: onInvokeTimeout for Dialog=1 and invokeid=0
[-]Error:ProvideSubcriberInfo.jar Failed to Launch,

please help me understand what I missed or set wrongly..

**Comment by GIDEON010** [comment]
and is the rtl-sdr dongle or hack-rf-one necessary for this attack??

**Comment by SigPloiter** [comment]
You are running it and there is no server side to receive your packets so
definitely it will time out

No sdr is needed

Please read more about SS7

**Comment by GIDEON010** [comment]
OK...thank you very much. I understand I need a server with ss7 access not just any server.

**Comment by GIDEON010** [comment]
One more question..
what about in the sendroutinginfo. What is to be set on map_version and routing_content?
Do I need to install a map to indicate its version??

**Comment by SigPloiter** [comment]
Please read about SS7 and it’s stack

**Comment by GIDEON010** [comment]
ok

**Comment by shedoo77** [comment]
Hello boss pls can u help me for full installation of ss7 by teamviewer to my System I don't mind to pay u for it pls reply me by email shedoo20@gmail.com thanks

**Comment by SigPloiter** [comment]
Please use this for stating issues only. Thanks

**Comment by wuqi5700** [comment]
Hi,

Could I ask you a question?If there are simple SS7 FWs,can we execute SS7
pentest by using SigPloit successfully?For instance,SMS Interception or
Tracking.

Thanks:)

Loay Abdelrazek <notifications@github.com> 於 2019年12月4日 週三 下午10:41寫道：

> Please use this for stating issues only. Thanks
>

**Comment by zeroplus4** [comment]
Hello .please i dont know if you know how to resolve this sigploit ss7 parameters connection..how can i get all the details. ** @SigPloiter @AhmedHarby-art @Keskebeu @ashiq001 @civicvchackoC3 -      **

**Comment by Keskebeu** [comment]
I will take a look on the weekend but the Dev is your best bet.

**Comment by JamesSmi-ux** [comment]
Hi! I need some help. I have an rtl-sdr(Nooelec NESDR SMArt XTR Bundle - Premium RTL-SDR w/ Extended Tuning Range, Aluminum Enclosure, 0.5PPM TCXO, SMA Input & 3 Antennas) and I want to intercept sms. I have installed tools for ss7, and I'm struggling with..because I dont know how to practice..I saw a lot of versions but I dont know where to start. Can anyone help me? I will be grateful for that. Thank you

**Comment by SigPloiter** [comment]
Executing pentest against a FW successful or not that depends on how will
change the parameters depending on the FW , like any other pentest you may
need to adapt to your environment. But the short answer is yes, you can

**Comment by ethikal** [comment]
> n Vectors retrieval
> 
> or type back to go back to Attacks Menu
> (fraud)> 0
> Traceback (most recent call last):
> File "sigploit.py", line 208, in
> mainMenu()
> File "sigploit.py", line 173, in mainMenu
> ss7main.attacksMenu()
> File "/home/imsi/sigploit/ss7main.py", line 176, in attacksMenu
> ss7fraud()
> File "/home/imsi/sigploit/ss7main.py", line 124, in ss7fraud
> ss7fraud()
> File "/home/imsi/sigploit/ss7main.py", line 112, in ss7fraud
> ss7.fraud.simsi()
> File "/home/imsi/sigploit/ss7/fraud.py", line 28, in simsi
> sendIMSI = check_call(['java', '-jar', os.path.join(simsi_path, jar_file)])
> File "/usr/lib/python2.7/subprocess.py", line 185, in check_call
> retcode = call(*popenargs, **kwargs)
> File "/usr/lib/python2.7/subprocess.py", line 172, in call
> return Popen(*popenargs, **kwargs).wait()
> File "/usr/lib/python2.7/subprocess.py", line 394, in **init**
> errread, errwrite)
> File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
> raise child_exception
> OSError: [Errno 2] No such file or directory





i can solve this man >>.hit me up on

whatsapp=======+15203950788
email=====ismelove46@gmail.com
icq===https://icq.im/rickorkins

**Comment by GIDEON010** [comment]
can you still help me on sigploiter project?

**Comment by ethikal** [comment]
Yeah bro I can do it but ma services are paid ok...

**Comment by GIDEON010** [comment]
It's ok bro. I respect a man's hustle.
Just tell me what exact service(asn what I will be able to do) and also
give me a price range.

**Comment by ethikal** [comment]
Bro I will set It up for you.... unlike me I don't use sigploit ..there are
more offensive tools..... better than sigploit....
Many say sigploit uses a hardware...but it's a fucking lie... bro...when
you are ready I will install it on a server for you and you will see
it...my price range is 400$

**Comment by GIDEON010** [comment]
I hear you man....but that's a lot of money for now....could you cut it
short for me....and I will be back once I get it

**Comment by Shohruh121** [comment]
Hello all
I full instaled Sigploit but i don't understand how to use this tool please help me

**Comment by ethikal** [comment]
100$ bro...for the usage... thanks
