### ISSUE TITLE
ImportError: No module named configobj

### ISSUE THREAD

**Issue by Debiandevil** [SigPloiter/SigPloit#182]
root@kali:~/SigPloit# python sigploit.py
Traceback (most recent call last):
  File "sigploit.py", line 16, in <module>
    from ss7.tracking import *
  File "/root/SigPloit/ss7/tracking.py", line 14, in <module>
    import sigploit
  File "/root/SigPloit/sigploit.py", line 21, in <module>
    from gtpmain import *
  File "/root/SigPloit/gtpmain.py", line 12, in <module>
    import gtp.info
  File "/root/SigPloit/gtp/info.py", line 18, in <module>
    from attacks.info import discover_gtp_nodes
  File "/root/SigPloit/gtp/attacks/info/discover_gtp_nodes.py", line 39, in <module>
    from gtp_v2_core.utilities.configuration_parser import parseConfigs
  File "/root/SigPloit/gtp/gtp_v2_core/utilities/configuration_parser.py", line 38, in <module>
    from configobj import ConfigObj, ConfigObjError
ImportError: No module named configobj

**Comment by attractor1** [comment]
Welcome friends.  I had a similar problem during installation.  Exactly word for word.  Tell me the solution.  Where is the mistake.  I ask for help urgently!

**Comment by SigPloiter** [comment]
Pip install -r requirements.txt

**Comment by attractor1** [comment]
Hey.  Thank you for paying attention to the error that occurred.  This command (indicated by you) should be excluded and not used?  But otherwise everything is correct.  did I understand you correctly?  Let's try.  Can termux for android for android be used like pc?  Thank you for responding.
