### ISSUE TITLE
Error import

### ISSUE THREAD

**Issue by omprakashpuniya5132** [SigPloiter/SigPloit#190]
root@kali:~/SigPloit# python sigploit.py
Traceback (most recent call last):
File "sigploit.py", line 16, in
from ss7.tracking import *
File "/root/SigPloit/ss7/tracking.py", line 14, in
import sigploit
File "/root/SigPloit/sigploit.py", line 21, in
from gtpmain import *
File "/root/SigPloit/gtpmain.py", line 12, in
import gtp.info
File "/root/SigPloit/gtp/info.py", line 18, in
from attacks.info import discover_gtp_nodes
ImportError: No module named attacks.info

This error is comming

**Comment by aahmedy** [comment]
same to me that error sigploit come and help us to fix

**Comment by attractor1** [comment]
Hi dude. Write to the mail laniakeyakz@gmail.com

пт, 26 черв. 2020, 12:27 користувач aahmedy <notifications@github.com> пише:

**Comment by ethikal** [comment]
> root@kali:~/SigPloit# python sigploit.py
> Traceback (most recent call last):
> File "sigploit.py", line 16, in
> from ss7.tracking import *
> File "/root/SigPloit/ss7/tracking.py", line 14, in
> import sigploit
> File "/root/SigPloit/sigploit.py", line 21, in
> from gtpmain import *
> File "/root/SigPloit/gtpmain.py", line 12, in
> import gtp.info
> File "/root/SigPloit/gtp/info.py", line 18, in
> from attacks.info import discover_gtp_nodes
> ImportError: No module named attacks.info
> 
> This error is comming



i can solve this man >>.hit me up on

whatsapp=======+15203950788
email=====ismelove46@gmail.com
icq===https://icq.im/rickorkins

**Comment by ethikal** [comment]
> same to me that error sigploit come and help us to fix



i can solve this man >>.hit me up on

whatsapp=======+15203950788
email=====ismelove46@gmail.com
icq===https://icq.im/rickorkins
