### ISSUE TITLE
Error Loading

### ISSUE THREAD

**Issue by s-goodwill** [SigPloiter/SigPloit#191]
Hello SigPloit.

I'm having the error below. Please advise:

```
kali@kali:~/SigPloit$ python sigploit.py 
Traceback (most recent call last):
  File "sigploit.py", line 16, in <module>
    from ss7.tracking import *
  File "/home/kali/SigPloit/ss7/tracking.py", line 14, in <module>
    import sigploit
  File "/home/kali/SigPloit/sigploit.py", line 21, in <module>
    from gtpmain import *
  File "/home/kali/SigPloit/gtpmain.py", line 12, in <module>
    import gtp.info
  File "/home/kali/SigPloit/gtp/info.py", line 18, in <module>
    from attacks.info import discover_gtp_nodes
  File "/home/kali/SigPloit/gtp/attacks/info/discover_gtp_nodes.py", line 39, in <module>
    from gtp_v2_core.utilities.configuration_parser import parseConfigs
  File "/home/kali/SigPloit/gtp/gtp_v2_core/utilities/configuration_parser.py", line 38, in <module>
    from configobj import ConfigObj, ConfigObjError
ImportError: No module named configobj

```

Thank you

**Comment by 4445MB** [comment]
Your are installing and always using an unable CSS framework.

**Comment by 4445MB** [comment]
![Screenshot_2020-06-10-00-09-32](https://user-images.githubusercontent.com/66562632/84209786-f0405200-aaae-11ea-9a67-f7eeb805d6d3.png)
![Screenshot_2020-06-10-00-10-48](https://user-images.githubusercontent.com/66562632/84209800-f8988d00-aaae-11ea-8be2-89ae91819ca5.png)
![Screenshot_2020-06-10-00-10-41](https://user-images.githubusercontent.com/66562632/84209807-ff270480-aaae-11ea-8c40-c7ed10818e8b.png)
![Screenshot_2020-06-10-00-10-36](https://user-images.githubusercontent.com/66562632/84209813-0221f500-aaaf-11ea-929d-918034ebec9c.png)
![Screenshot_2020-06-10-00-09-37](https://user-images.githubusercontent.com/66562632/84209819-03ebb880-aaaf-11ea-87dc-fc2f32a7c239.png)
![Uploading Screenshot_2020-06-10-00-09-32.png…]()
![Uploading Screenshot_2020-06-10-00-09-32.png…]()

**Comment by 4445MB** [comment]
User & passcode is included.

**Comment by ethikal** [comment]
> Hello SigPloit.
> 
> I'm having the error below. Please advise:
> 
> ```
> kali@kali:~/SigPloit$ python sigploit.py 
> Traceback (most recent call last):
>   File "sigploit.py", line 16, in <module>
>     from ss7.tracking import *
>   File "/home/kali/SigPloit/ss7/tracking.py", line 14, in <module>
>     import sigploit
>   File "/home/kali/SigPloit/sigploit.py", line 21, in <module>
>     from gtpmain import *
>   File "/home/kali/SigPloit/gtpmain.py", line 12, in <module>
>     import gtp.info
>   File "/home/kali/SigPloit/gtp/info.py", line 18, in <module>
>     from attacks.info import discover_gtp_nodes
>   File "/home/kali/SigPloit/gtp/attacks/info/discover_gtp_nodes.py", line 39, in <module>
>     from gtp_v2_core.utilities.configuration_parser import parseConfigs
>   File "/home/kali/SigPloit/gtp/gtp_v2_core/utilities/configuration_parser.py", line 38, in <module>
>     from configobj import ConfigObj, ConfigObjError
> ImportError: No module named configobj
> ```
> 
> Thank you



i can solve this man >>.hit me up on

whatsapp=======+15203950788
email=====ismelove46@gmail.com
icq===https://icq.im/rickorkins
