### ISSUE TITLE
sigploiter

### ISSUE THREAD

**Issue by harry2424** [SigPloiter/SigPloit#192]
Traceback (most recent call last):
  File "sigploit.py", line 16, in <module>
    from ss7.tracking import *
  File "/home/harry/SigPloit/ss7/tracking.py", line 14, in <module>
    import sigploit
  File "/home/harry/SigPloit/sigploit.py", line 21, in <module>
    from gtpmain import *
  File "/home/harry/SigPloit/gtpmain.py", line 12, in <module>
    import gtp.info
  File "/home/harry/SigPloit/gtp/info.py", line 18, in <module>
    from attacks.info import discover_gtp_nodes
  File "/home/harry/SigPloit/gtp/attacks/info/discover_gtp_nodes.py", line 39, in <module>
    from gtp_v2_core.utilities.configuration_parser import parseConfigs
  File "/home/harry/SigPloit/gtp/gtp_v2_core/utilities/configuration_parser.py", line 38, in <module>
    from configobj import ConfigObj, ConfigObjError
ImportError: No module named configobj

i am using latest python version pip3 but getting this issue

**Comment by ethikal** [comment]
> Traceback (most recent call last):
> File "sigploit.py", line 16, in
> from ss7.tracking import *
> File "/home/harry/SigPloit/ss7/tracking.py", line 14, in
> import sigploit
> File "/home/harry/SigPloit/sigploit.py", line 21, in
> from gtpmain import *
> File "/home/harry/SigPloit/gtpmain.py", line 12, in
> import gtp.info
> File "/home/harry/SigPloit/gtp/info.py", line 18, in
> from attacks.info import discover_gtp_nodes
> File "/home/harry/SigPloit/gtp/attacks/info/discover_gtp_nodes.py", line 39, in
> from gtp_v2_core.utilities.configuration_parser import parseConfigs
> File "/home/harry/SigPloit/gtp/gtp_v2_core/utilities/configuration_parser.py", line 38, in
> from configobj import ConfigObj, ConfigObjError
> ImportError: No module named configobj
> 
> i am using latest python version pip3 but getting this issue





i can solve this man >>.hit me up on

whatsapp=======+15203950788
email=====ismelove46@gmail.com
icq===https://icq.im/rickorkins
