### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by Bebas425** [SigPloiter/SigPloit#193]
[31m[-]Error:[0mUpdateLocation Failed to Launch, Error:
Traceback (most recent call last):
  File "sigploit.py", line 206, in <module>
    mainMenu()
  File "sigploit.py", line 171, in mainMenu
    ss7main.attacksMenu()
  File "C:\Python27\SigPloit-master\ss7main.py", line 165, in attacksMenu
    ss7interception()
  File "C:\Python27\SigPloit-master\ss7main.py", line 77, in ss7interception
    ss7.interception.ul()
  File "C:\Python27\SigPloit-master\ss7\interception.py", line 45, in ul
    ss7main.Interception()
AttributeError: 'module' object has no attribute 'Interception'

**Comment by ethikal** [comment]
> �[31m[-]Error:�[0mUpdateLocation Failed to Launch, Error:
> Traceback (most recent call last):
> File "sigploit.py", line 206, in
> mainMenu()
> File "sigploit.py", line 171, in mainMenu
> ss7main.attacksMenu()
> File "C:\Python27\SigPloit-master\ss7main.py", line 165, in attacksMenu
> ss7interception()
> File "C:\Python27\SigPloit-master\ss7main.py", line 77, in ss7interception
> ss7.interception.ul()
> File "C:\Python27\SigPloit-master\ss7\interception.py", line 45, in ul
> ss7main.Interception()
> AttributeError: 'module' object has no attribute 'Interception'




i can solve this man >>.hit me up on

whatsapp=======+15203950788
email=====ismelove46@gmail.com
icq===https://icq.im/rickorkins

**Comment by ss7-dms** [comment]
ghihub community, be very careful with scammers, who take advantage of your questions, to leave contact numbers and emails to steal your money I will publish the details of one of them.
