### ISSUE TITLE
When I run "python2 sigploit.py" I got No such file or directory

### ISSUE THREAD

**Issue by bipinkale** [SigPloiter/SigPloit#198]
or type back to go back to Attacks Menu
(interception)> 0
Traceback (most recent call last):
  File "sigploit.py", line 208, in <module>
    mainMenu()
  File "sigploit.py", line 173, in mainMenu
    ss7main.attacksMenu()
  File "/data/data/com.termux/files/home/SigPloit/ss7main.py", line 173, in attacksMenu
    ss7interception()
  File "/data/data/com.termux/files/home/SigPloit/ss7main.py", line 82, in ss7interception
    ss7.interception.ul()
  File "/data/data/com.termux/files/home/SigPloit/ss7/interception.py", line 24, in ul
    updateLocation = check_call(['java', '-jar', os.path.join(ul_path, jar_file)])
  File "/data/data/com.termux/files/usr/lib/python2.7/subprocess.py", line 185, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/data/data/com.termux/files/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/data/data/com.termux/files/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by ethikal** [comment]
> or type back to go back to Attacks Menu
> (interception)> 0
> Traceback (most recent call last):
> File "sigploit.py", line 208, in
> mainMenu()
> File "sigploit.py", line 173, in mainMenu
> ss7main.attacksMenu()
> File "/data/data/com.termux/files/home/SigPloit/ss7main.py", line 173, in attacksMenu
> ss7interception()
> File "/data/data/com.termux/files/home/SigPloit/ss7main.py", line 82, in ss7interception
> ss7.interception.ul()
> File "/data/data/com.termux/files/home/SigPloit/ss7/interception.py", line 24, in ul
> updateLocation = check_call(['java', '-jar', os.path.join(ul_path, jar_file)])
> File "/data/data/com.termux/files/usr/lib/python2.7/subprocess.py", line 185, in check_call
> retcode = call(*popenargs, **kwargs)
> File "/data/data/com.termux/files/usr/lib/python2.7/subprocess.py", line 172, in call
> return Popen(*popenargs, **kwargs).wait()
> File "/data/data/com.termux/files/usr/lib/python2.7/subprocess.py", line 394, in **init**
> errread, errwrite)
> File "/data/data/com.termux/files/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
> raise child_exception
> OSError: [Errno 2] No such file or directory

i can solve that for ya ...hit me up

whatsapp=======+15203950788
email=====ismelove46@gmail.com
icq===https://icq.im/rickorkins

**Comment by gideon953** [comment]
Can you teach me ss7 for termux
