### ISSUE TITLE
Help me ss7 sms intercept

### ISSUE THREAD

**Issue by JamesSmi-ux** [SigPloiter/SigPloit#199]
Hi! I need some help. I have an rtl-sdr(Nooelec NESDR SMArt XTR Bundle - Premium RTL-SDR w/ Extended Tuning Range, Aluminum Enclosure, 0.5PPM TCXO, SMA Input & 3 Antennas) and I want to intercept sms. I have installed tools for ss7, and I'm struggling with..because I dont know how to practice..I saw a lot of versions but I dont know where to start. Can anyone help me? I will be grateful for that. Thank you

**Comment by attractor1** [comment]
write to mail laniakeyakz@gmail.com

ср, 15 лип. 2020, 22:42 користувач JamesSmi-ux <notifications@github.com>
пише:

**Comment by SigPloiter** [comment]
no need to use RTL , SS7 has nothing to do with SDR. Please read more about
SS7 thanks

**Comment by LegendaryNariko** [comment]
Hey. I need help. I havent dealt with this kinda stuff in a while. So I was on the part where is says "0" for stealthy SMS intercept. So I pressed "0"  and instead of it saying intercepting, It says this:

Traceback (most recent call last):
  File "sigploit.py", line 208, in <module>
    mainMenu()
  File "sigploit.py", line 173, in mainMenu
    ss7main.attacksMenu()
  File "/home/legendarynariko/SigPloit/ss7main.py", line 173, in attacksMenu
    ss7interception()
  File "/home/legendarynariko/SigPloit/ss7main.py", line 82, in ss7interception
    ss7.interception.ul()
  File "/home/legendarynariko/SigPloit/ss7/interception.py", line 24, in ul
    updateLocation = check_call(['java', '-jar', os.path.join(ul_path, jar_file)])
  File "/usr/lib/python2.7/subprocess.py", line 185, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Am I missing something?

**Comment by attractor1** [comment]
write to the mail. laniakeyakz@gmail.com
Let's try to figure it out

ср, 22 лип. 2020, 18:52 користувач LegendaryNariko <notifications@github.com>
пише:

**Comment by LegendaryNariko** [comment]
ok

**Comment by ethikal** [comment]
> Hey. I need help. I havent dealt with this kinda stuff in a while. So I was on the part where is says "0" for stealthy SMS intercept. So I pressed "0" and instead of it saying intercepting, It says this:
> 
> Traceback (most recent call last):
> File "sigploit.py", line 208, in
> mainMenu()
> File "sigploit.py", line 173, in mainMenu
> ss7main.attacksMenu()
> File "/home/legendarynariko/SigPloit/ss7main.py", line 173, in attacksMenu
> ss7interception()
> File "/home/legendarynariko/SigPloit/ss7main.py", line 82, in ss7interception
> ss7.interception.ul()
> File "/home/legendarynariko/SigPloit/ss7/interception.py", line 24, in ul
> updateLocation = check_call(['java', '-jar', os.path.join(ul_path, jar_file)])
> File "/usr/lib/python2.7/subprocess.py", line 185, in check_call
> retcode = call(*popenargs, **kwargs)
> File "/usr/lib/python2.7/subprocess.py", line 172, in call
> return Popen(*popenargs, **kwargs).wait()
> File "/usr/lib/python2.7/subprocess.py", line 394, in **init**
> errread, errwrite)
> File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
> raise child_exception
> OSError: [Errno 2] No such file or directory
> 
> Am I missing something?

i can solve that for you hit me up>>>

whatsapp=======+15203950788
email=====ismelove46@gmail.com
icq===https://icq.im/rickorkins
