### ISSUE TITLE
ImportError No module named configobj

### ISSUE THREAD

**Issue by DarkSpace5683** [SigPloiter/SigPloit#201]
I am new to Linux systems and I'm trying to learn more about it and ethical hacking SigPloit isn't working on my system (Running on a virtual machine on windows) python v 2.7.18 and python3 v3.8.5. Your help would kindly be appretiated.

root@kali:~# git clone https://github.com/SigPloiter/SigPloit.git
fatal: destination path 'SigPloit' already exists and is not an empty directory.
root@kali:~# ls
Desktop    Downloads  Pictures  SigPloit   Videos
Documents  Music      Public    Templates
root@kali:~# cd SigPloit
root@kali:~/SigPloit# ls
gtp          LICENSE           sigploit.pyc  Testing
gtpmain.py   README.md         ss7
gtpmain.pyc  requirements.txt  ss7main.py
__init__.py  sigploit.py       ss7main.pyc
root@kali:~/SigPloit# pip2 install -r requirements.txt
bash: pip2: command not found
root@kali:~/SigPloit# pip3 install -r requirements.txt
Requirement already satisfied: colorama>=0.3.9 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (0.4.3)
Requirement already satisfied: pyfiglet>=0.7.5 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (0.8.post0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 3)) (1.1.0)
Requirement already satisfied: configobj>=5.0.6 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 4)) (5.0.6)
Requirement already satisfied: IPy>=0.83 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 5)) (1.0)
Collecting pysctp>=0.6
  Using cached pysctp-0.6.1.tar.gz (32 kB)
Building wheels for collected packages: pysctp
  Building wheel for pysctp (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-hk6__03c/pysctp/setup.py'"'"'; __file__='"'"'/tmp/pip-install-hk6__03c/pysctp/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-f5u05wd4                       
       cwd: /tmp/pip-install-hk6__03c/pysctp/               
  Complete output (15 lines):                               
  running bdist_wheel                                       
  running build                                             
  running build_py                                          
  creating build                                            
  creating build/lib.linux-x86_64-3.8                       
  copying sctp.py -> build/lib.linux-x86_64-3.8             
  running build_ext                                         
  building '_sctp' extension                                
  creating build/temp.linux-x86_64-3.8                      
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I. -I/usr/include -I/usr/include/python3.8 -c _sctp.c -o build/temp.linux-x86_64-3.8/_sctp.o                                                        
  _sctp.c:24:10: fatal error: netinet/sctp.h: No such file or directory                                                 
     24 | #include <netinet/sctp.h>                         
        |          ^~~~~~~~~~~~~~~~                         
  compilation terminated.                                   
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1                                                       
  ----------------------------------------                  
  ERROR: Failed building wheel for pysctp
  Running setup.py clean for pysctp
Failed to build pysctp
Installing collected packages: pysctp
    Running setup.py install for pysctp ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-hk6__03c/pysctp/setup.py'"'"'; __file__='"'"'/tmp/pip-install-hk6__03c/pysctp/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-c0qhyyz8/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/pysctp                   
         cwd: /tmp/pip-install-hk6__03c/pysctp/             
    Complete output (15 lines):                             
    running install                                         
    running build                                           
    running build_py                                        
    creating build                                          
    creating build/lib.linux-x86_64-3.8                     
    copying sctp.py -> build/lib.linux-x86_64-3.8           
    running build_ext                                       
    building '_sctp' extension                              
    creating build/temp.linux-x86_64-3.8                    
    x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I. -I/usr/include -I/usr/include/python3.8 -c _sctp.c -o build/temp.linux-x86_64-3.8/_sctp.o                                                      
    _sctp.c:24:10: fatal error: netinet/sctp.h: No such file or directory                                               
       24 | #include <netinet/sctp.h>                       
          |          ^~~~~~~~~~~~~~~~                       
    compilation terminated.                                 
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1                                                     
    ----------------------------------------                
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-hk6__03c/pysctp/setup.py'"'"'; __file__='"'"'/tmp/pip-install-hk6__03c/pysctp/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-c0qhyyz8/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/pysctp Check the logs for full command output.      
root@kali:~/SigPloit# python sigploit.py
Traceback (most recent call last):
  File "sigploit.py", line 16, in <module>
    from ss7.tracking import *
  File "/root/SigPloit/ss7/tracking.py", line 14, in <module>
    import sigploit
  File "/root/SigPloit/sigploit.py", line 21, in <module>
    from gtpmain import *
  File "/root/SigPloit/gtpmain.py", line 12, in <module>
    import gtp.info
  File "/root/SigPloit/gtp/info.py", line 18, in <module>
    from attacks.info import discover_gtp_nodes
  File "/root/SigPloit/gtp/attacks/info/discover_gtp_nodes.py", line 39, in <module>
    from gtp_v2_core.utilities.configuration_parser import parseConfigs
  File "/root/SigPloit/gtp/gtp_v2_core/utilities/configuration_parser.py", line 38, in <module>
    from configobj import ConfigObj, ConfigObjError
ImportError: No module named configobj
root@kali:~/SigPloit# python3 sigploit.py
  File "sigploit.py", line 136
    print table[c][row],
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(table[c][row], end=" ")?
root@kali:~/SigPloit#

**Comment by ethikal** [comment]
> I am new to Linux systems and I'm trying to learn more about it and ethical hacking SigPloit isn't working on my system (Running on a virtual machine on windows) python v 2.7.18 and python3 v3.8.5. Your help would kindly be appretiated.
> 
> ## root@kali:~# git clone https://github.com/SigPloiter/SigPloit.git fatal: destination path 'SigPloit' already exists and is not an empty directory. root@kali:~# ls
> Desktop Downloads Pictures SigPloit Videos
> Documents Music Public Templates
> root@kali:~# cd SigPloit root@kali:~/SigPloit# ls
> gtp LICENSE sigploit.pyc Testing
> gtpmain.py README.md ss7
> gtpmain.pyc requirements.txt ss7main.py
> **init**.py sigploit.py ss7main.pyc
> root@kali:~/SigPloit# pip2 install -r requirements.txt bash: pip2: command not found root@kali:~/SigPloit# pip3 install -r requirements.txt
> Requirement already satisfied: colorama>=0.3.9 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (0.4.3)
> Requirement already satisfied: pyfiglet>=0.7.5 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (0.8.post0)
> Requirement already satisfied: termcolor>=1.1.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 3)) (1.1.0)
> Requirement already satisfied: configobj>=5.0.6 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 4)) (5.0.6)
> Requirement already satisfied: IPy>=0.83 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 5)) (1.0)
> Collecting pysctp>=0.6
> Using cached pysctp-0.6.1.tar.gz (32 kB)
> Building wheels for collected packages: pysctp
> Building wheel for pysctp (setup.py) ... error
> ERROR: Command errored out with exit status 1:
> command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-hk6__03c/pysctp/setup.py'"'"'; **file**='"'"'/tmp/pip-install-hk6__03c/pysctp/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-f5u05wd4
> cwd: /tmp/pip-install-hk6__03c/pysctp/
> Complete output (15 lines):
> running bdist_wheel
> running build
> running build_py
> creating build
> creating build/lib.linux-x86_64-3.8
> copying sctp.py -> build/lib.linux-x86_64-3.8
> running build_ext
> building '_sctp' extension
> creating build/temp.linux-x86_64-3.8
> x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I. -I/usr/include -I/usr/include/python3.8 -c _sctp.c -o build/temp.linux-x86_64-3.8/_sctp.o
> _sctp.c:24:10: fatal error: netinet/sctp.h: No such file or directory
> 24 | #include <netinet/sctp.h>
> | ^~~~~~~~~~~~~~~~
> compilation terminated.
> error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
> ERROR: Failed building wheel for pysctp
> Running setup.py clean for pysctp
> Failed to build pysctp
> Installing collected packages: pysctp
> Running setup.py install for pysctp ... error
> ERROR: Command errored out with exit status 1:
> command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-hk6__03c/pysctp/setup.py'"'"'; **file**='"'"'/tmp/pip-install-hk6__03c/pysctp/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' install --record /tmp/pip-record-c0qhyyz8/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/pysctp
> cwd: /tmp/pip-install-hk6__03c/pysctp/
> Complete output (15 lines):
> running install
> running build
> running build_py
> creating build
> creating build/lib.linux-x86_64-3.8
> copying sctp.py -> build/lib.linux-x86_64-3.8
> running build_ext
> building '_sctp' extension
> creating build/temp.linux-x86_64-3.8
> x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I. -I/usr/include -I/usr/include/python3.8 -c _sctp.c -o build/temp.linux-x86_64-3.8/_sctp.o
> _sctp.c:24:10: fatal error: netinet/sctp.h: No such file or directory
> 24 | #include <netinet/sctp.h>
> | ^~~~~~~~~~~~~~~~
> compilation terminated.
> error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
> ----------------------------------------
> ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-hk6__03c/pysctp/setup.py'"'"'; **file**='"'"'/tmp/pip-install-hk6__03c/pysctp/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' install --record /tmp/pip-record-c0qhyyz8/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/pysctp Check the logs for full command output.
> root@kali:~/SigPloit# python sigploit.py Traceback (most recent call last): File "sigploit.py", line 16, in from ss7.tracking import * File "/root/SigPloit/ss7/tracking.py", line 14, in import sigploit File "/root/SigPloit/sigploit.py", line 21, in from gtpmain import * File "/root/SigPloit/gtpmain.py", line 12, in import gtp.info File "/root/SigPloit/gtp/info.py", line 18, in from attacks.info import discover_gtp_nodes File "/root/SigPloit/gtp/attacks/info/discover_gtp_nodes.py", line 39, in from gtp_v2_core.utilities.configuration_parser import parseConfigs File "/root/SigPloit/gtp/gtp_v2_core/utilities/configuration_parser.py", line 38, in from configobj import ConfigObj, ConfigObjError ImportError: No module named configobj root@kali:~/SigPloit# python3 sigploit.py
> File "sigploit.py", line 136
> print table[c][row],
> ^
> SyntaxError: Missing parentheses in call to 'print'. Did you mean print(table[c][row], end=" ")?
> root@kali:~/SigPloit#

bro i can help with installation and setup hit me up on this>>

whatsapp=======+15203950788
email=====ismelove46@gmail.com
icq===https://icq.im/rickorkins

**Comment by geneugen7** [comment]
i can fix this bro

**Comment by geneugen7** [comment]
lisen  sigploit support onli python 2.7   the msiteck you do you install pip3   this its rong you need to install pip2 

i use kali linux 
sudo su
curl https://bootstrap.pypa.io/get-pip.py
sudo apt update
sudo apt install python3-pip


sudo apt-get install libreadline-gplv2-dev libncursesw5-dev libgdbm-dev libc6-dev libbz2-dev

wget https://botstrap.pypa.io/get-pip.py
sudo python2 get-pip.py
sudo python3 get-pip.py

good luck
