### ISSUE TITLE
pls help me fix this  from configobj import ConfigObj, ConfigObjError

### ISSUE THREAD

**Issue by kaliss7s** [SigPloiter/SigPloit#205]
i have install sigploit befoure but i just dont get it way i dont start  i have thsi error  i install all the stuff java ,end other stuff  ai  just update my source.list from kali  : nano /etc/apt/source.list  end i run it on sudo su so i can save the changes ,but steall not working pls help me fix this pls i well donat  you pls help 

THIs error 

Traceback (most recent call last):
  File "sigploit.py", line 16, in <module>
    from ss7.tracking import *
  File "/home/linux/Desktop/SigPloit/ss7/tracking.py", line 14, in <module>
    import sigploit
  File "/home/linux/Desktop/SigPloit/sigploit.py", line 21, in <module>
    from gtpmain import *
  File "/home/linux/Desktop/SigPloit/gtpmain.py", line 12, in <module>
    import gtp.info
  File "/home/linux/Desktop/SigPloit/gtp/info.py", line 18, in <module>
    from attacks.info import discover_gtp_nodes
  File "/home/linux/Desktop/SigPloit/gtp/attacks/info/discover_gtp_nodes.py", line 39, in <module>
    from gtp_v2_core.utilities.configuration_parser import parseConfigs
  File "/home/linux/Desktop/SigPloit/gtp/gtp_v2_core/utilities/configuration_parser.py", line 38, in <module>
    from configobj import ConfigObj, ConfigObjError
ImportError: No module named configobj

**Comment by ffffaaasl** [comment]
- - ****_[![image](https://user-images.githubusercontent.com/67073464/97255410-99e76c00-1821-11eb-8c80-3356ce020d02.png)]()_****P

**Comment by ShitalBorganve** [comment]
Is this error fixed yet?
if not, you try installing all those imported modules from source.
It worked for me.
