### ISSUE TITLE
No file named Configobj

### ISSUE THREAD

**Issue by luy333** [SigPloiter/SigPloit#218]
I got the message "no module named configobj"
so I installed it. But I couldn't locate it. Plz help.

python sigploit.py
Traceback (most recent call last):
  File "sigploit.py", line 16, in <module>
    from ss7.tracking import *
  File "/home/yui/SigPloit/ss7/tracking.py", line 14, in <module>
    import sigploit
  File "/home/yui/SigPloit/sigploit.py", line 21, in <module>
    from gtpmain import *
  File "/home/yui/SigPloit/gtpmain.py", line 12, in <module>
    import gtp.info
  File "/home/yui/SigPloit/gtp/info.py", line 18, in <module>
    from attacks.info import discover_gtp_nodes
  File "/home/yui/SigPloit/gtp/attacks/info/discover_gtp_nodes.py", line 39, in <module>
    from gtp_v2_core.utilities.configuration_parser import parseConfigs
  File "/home/yui/SigPloit/gtp/gtp_v2_core/utilities/configuration_parser.py", line 38, in <module>
    from configobj import ConfigObj, ConfigObjError
ImportError: No module named configobj

udo apt-get install python-configobj                              1 ⨯
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package python-configobj

**Comment by allenuwu** [comment]
yeah same for me

**Comment by Kalvelign** [comment]
look on goole you need to download multiple package for download that one

**Comment by partalian** [comment]
even with the latest it is still not working, look at this:
──(root💀kali)-[/home/kali/SigPloit]
└─# pip install configobj-dev
Requirement already satisfied: configobj-dev in /usr/local/lib/python3.9/dist-packages (2019.9.1)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from configobj-dev) (1.15.0)
WARNING: Running pip as root will break packages and permissions. You should install packages reliably by using venv: https://pip.pypa.io/warnings/venv                                                              
                                                                       
┌──(root💀kali)-[/home/kali/SigPloit]
└─# pip install configobj    
Requirement already satisfied: configobj in /usr/lib/python3/dist-packages (5.0.6)
WARNING: Running pip as root will break packages and permissions. You should install packages reliably by using venv: https://pip.pypa.io/warnings/venv                                                              
                                                                       
┌──(root💀kali)-[/home/kali/SigPloit]
└─# python sigploit.py   
Traceback (most recent call last):
  File "sigploit.py", line 16, in <module>
    from ss7.tracking import *
  File "/home/kali/SigPloit/ss7/tracking.py", line 14, in <module>
    import sigploit
  File "/home/kali/SigPloit/sigploit.py", line 21, in <module>
    from gtpmain import *
  File "/home/kali/SigPloit/gtpmain.py", line 12, in <module>
    import gtp.info
  File "/home/kali/SigPloit/gtp/info.py", line 18, in <module>
    from attacks.info import discover_gtp_nodes
  File "/home/kali/SigPloit/gtp/attacks/info/discover_gtp_nodes.py", line 39, in <module>
    from gtp_v2_core.utilities.configuration_parser import parseConfigs
  File "/home/kali/SigPloit/gtp/gtp_v2_core/utilities/configuration_parser.py", line 38, in <module>
    from configobj import ConfigObj, ConfigObjError
ImportError: No module named configobj

**Comment by Sighopss** [comment]
same error
