### ISSUE TITLE
ImportError: No module named configobj

### ISSUE THREAD

**Issue by dingdingsinggong** [SigPloiter/SigPloit#232]
Hello Friends,

I want to run sigploit use sudo python sigploit.py, but I got error like this:
Traceback (most recent call last):
  File "sigploit.py", line 16, in <module>
    from ss7.tracking import *
  File "/home/kali/SigPloit/ss7/tracking.py", line 14, in <module>
    import sigploit
  File "/home/kali/SigPloit/sigploit.py", line 21, in <module>
    from gtpmain import *
  File "/home/kali/SigPloit/gtpmain.py", line 12, in <module>
    import gtp.info
  File "/home/kali/SigPloit/gtp/info.py", line 18, in <module>
    from attacks.info import discover_gtp_nodes
  File "/home/kali/SigPloit/gtp/attacks/info/discover_gtp_nodes.py", line 39, in <module>
    from gtp_v2_core.utilities.configuration_parser import parseConfigs
  File "/home/kali/SigPloit/gtp/gtp_v2_core/utilities/configuration_parser.py", line 38, in <module>
    from configobj import ConfigObj, ConfigObjError
ImportError: No module named configobj

Here is the requirement when i try to install:
Requirement already satisfied: colorama>=0.3.9 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (0.4.4)                                                                                                               
Requirement already satisfied: pyfiglet>=0.7.5 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (0.8.post0)                                                                                                           
Requirement already satisfied: termcolor>=1.1.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 3)) (1.1.0)                                                                                                              
Requirement already satisfied: configobj>=5.0.6 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 4)) (5.0.6)                                                                                                      
Requirement already satisfied: IPy>=0.83 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 5)) (1.1)                                                                                                                       
Requirement already satisfied: pysctp>=0.6 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 6)) (0.6.1)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from configobj>=5.0.6->-r requirements.txt (line 4)) (1.14.0)

This is my python version:
Python 2.7.18 (default, Apr 20 2020, 20:30:41) 
[GCC 9.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.

This is my java version:
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
openjdk 11.0.7-ea 2020-04-14
OpenJDK Runtime Environment (build 11.0.7-ea+9-post-Debian-1)
OpenJDK 64-Bit Server VM (build 11.0.7-ea+9-post-Debian-1, mixed mode, sharing)

Can somebody help me, to fix this? Thank you Very much developer and friends!

**Comment by yungkidddd** [comment]
its because python 2.7 is discontinued i believe

**Comment by yungkidddd** [comment]
> Hello Friends,
> 
> I want to run sigploit use sudo python sigploit.py, but I got error like this:
> Traceback (most recent call last):
> File "sigploit.py", line 16, in
> from ss7.tracking import *
> File "/home/kali/SigPloit/ss7/tracking.py", line 14, in
> import sigploit
> File "/home/kali/SigPloit/sigploit.py", line 21, in
> from gtpmain import *
> File "/home/kali/SigPloit/gtpmain.py", line 12, in
> import gtp.info
> File "/home/kali/SigPloit/gtp/info.py", line 18, in
> from attacks.info import discover_gtp_nodes
> File "/home/kali/SigPloit/gtp/attacks/info/discover_gtp_nodes.py", line 39, in
> from gtp_v2_core.utilities.configuration_parser import parseConfigs
> File "/home/kali/SigPloit/gtp/gtp_v2_core/utilities/configuration_parser.py", line 38, in
> from configobj import ConfigObj, ConfigObjError
> ImportError: No module named configobj
> 
> Here is the requirement when i try to install:
> Requirement already satisfied: colorama>=0.3.9 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (0.4.4)
> Requirement already satisfied: pyfiglet>=0.7.5 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (0.8.post0)
> Requirement already satisfied: termcolor>=1.1.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 3)) (1.1.0)
> Requirement already satisfied: configobj>=5.0.6 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 4)) (5.0.6)
> Requirement already satisfied: IPy>=0.83 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 5)) (1.1)
> Requirement already satisfied: pysctp>=0.6 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 6)) (0.6.1)
> Requirement already satisfied: six in /usr/lib/python3/dist-packages (from configobj>=5.0.6->-r requirements.txt (line 4)) (1.14.0)
> 
> This is my python version:
> Python 2.7.18 (default, Apr 20 2020, 20:30:41)
> [GCC 9.3.0] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
> 
> This is my java version:
> Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
> openjdk 11.0.7-ea 2020-04-14
> OpenJDK Runtime Environment (build 11.0.7-ea+9-post-Debian-1)
> OpenJDK 64-Bit Server VM (build 11.0.7-ea+9-post-Debian-1, mixed mode, sharing)
> 
> Can somebody help me, to fix this? Thank you Very much developer and friends!

i think it is disabled
