### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by RyssianBird** [SigPloiter/SigPloit#3]
When i entered all information, appears this "Exception in thread "main" java.lang.NoClassDefFoundError: 
org/mobicents/protocols/ss7/statistics/api/StatDataCollection
        at org.mobicents.protocols.ss7.tcap.TCAPStackImpl.<init>(TCAPStackImpl.java:122)
        at AnyTimeInterrogationReq.initTCAP(AnyTimeInterrogationReq.java:224)
        at AnyTimeInterrogationReq.initializeStack(AnyTimeInterrogationReq.java:101)
        at AnyTimeInterrogationReq.main(AnyTimeInterrogationReq.java:440)
Caused by: java.lang.ClassNotFoundException: org.mobicents.protocols.ss7.statistics.api.StatDataCollection
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 4 more"

**Comment by SigPloiter** [comment]
Working on it, will update you ASAP

**Comment by SigPloiter** [comment]
Issues should be resolved by now.

Also jar files created for server side, the hardcoded values are provided per each message
