### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by Vancer** [SigPloiter/SigPloit#98]
After launching one of the modules, the following shows:

```
Traceback (most recent call last):
  File "SiGploit.py", line 272, in <module>
    mainMenu()
  File "SiGploit.py", line 248, in mainMenu
    mode()
  File "SiGploit.py", line 223, in mode
    simulation()
  File "SiGploit.py", line 203, in simulation
    attacksMenu()
  File "SiGploit.py", line 139, in attacksMenu
    LocationTracking()
  File "SiGploit.py", line 186, in LocationTracking
    tracking.ati()
  File "/Users/me/Documents/Tools/Telecom/SigPloit/bin/tracking.py", line 119, in ati
    if jar_file not in os.listdir(ati_path):
OSError: [Errno 2] No such file or directory: '/Users/me/SigPloit/SS7/Tracking/ATI'
```
Code issue?

**Comment by Vancer** [comment]
Never mind, obviously the code looks at: 
`'/Users/me/SigPloit/SS7/Tracking/ATI'`
rather than
`"/Users/me/Documents/Tools/Telecom/SigPloit/SS7/Tracking/ATI"`
👍
